### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by chpatrick** [system123/ceres_extensions#3]
Hi, we'd like to use this code but we're unsure about its license. Would it be possible to license it under the MIT license?

EDIT: or the New BSD license, like [Ceres itself](http://ceres-solver.org/license.html).

**Comment by system123** [comment]
I have uploaded the license agreement.

**Comment by chpatrick** [comment]
Thanks, Lloyd!

We're making a structure from motion system in Haskell and wanted to use
Eigen on the C++ side. :)

**Comment by system123** [comment]
body { margin:0 !important; }
div[style*="margin: 16px 0"] { margin:0 !important; font-size:100% !important; }
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {margin: 0;padding: 0;}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}
img-apps { padding:0 5px 0 0;}

a.mobile-button:link, a.mobile-button:visited { color:#fff!important;}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 9px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

has invited you to this exclusive free trial
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=7&amp;authToken=S1TP25uc97B7W3SprZLsFUA6LqAKYcHU4Os6xbfd5aGT8F6aIvBDS7OgpJRYv%2f7yjS9PdZFdzcNKsQrEHT84ZenZud5aNf9cRp1q8w%2fg%2fo7I47%2fJuS72aq1qRfh5BHoqhHbn210DMJYCv%2bj%2b230wiBHvjP8vogxm2RA384ysTBZpNvl%2fsCudSgDhqk39Nc3HPefuDS2V%2bkzBtE%2fV6%2fbOxhHHzYx05MwWbX52auRfEZADnW7%2bBFAyzOToiuvMPYAaHCRjPv6RaZMMCW2hyZPFwppWDahaGMoOwF1o5xNIn3cHrv%2b6%2fdcw3uY8YVIJpJ%2fg&amp;PolicyAcceptance=v5GMmZPXZd1VDiXFGf73csSXEXvQd6RKBllCkpojF3gh93S62uXcRoPRQcGH5c6J%2fs0NPcklk73cGiDULqKkUeLBNhcXb0G4b9VmI64qjsVZtbjPvrRyrSmAT0euoaQoSw4nrKBEg896CugZApJc1oscOOxiNSgemnDQthffOMMKcmDqTVPRTxwced6K4ysZ03MlqRiXg22%2bRnkOkEBkL0pfui3GBd1fRn9A5FbiPeSQyVYqQS0MlwudQZ9v6uwOcbksGusJqBslUXfXKVTRtCj9wmOrTmXgmt2h5FYfza%2frQiMl3IMXb6rsM%2blRX%2fqZ%2bhvdPIpa2fuNKFa1EG5H54knpxYhvL9FOXtyZxgxaNrdIXYfGgIyuLfGWWzx7EjfMsS27PoIWPs3e1cVnpYYokm6bfkYKlw3Wk9K2BZA2w%2bQz02UUl2a6I%2flmrI6AeBtAUnmSdtiLUVuM2gdIkIzuvJyQSIW1oM5dE54sya9S48OHxUD58wZYI9yPupnhH2NIg6G1I85yxnqv1jJi2QhW5fzt6WmqjVD5%2bLDIP6unoW3qtNXplK49XhA1gy%2bns0prhILyPgfGD%2bZxwO7KGmZLCKaOU1tRFIZsVp9o2x1lb4k2%2b0IslTxkO22fy6ralpStjEBCsb3p94aKjATmNYt%2bNttLVaB7Q8Z2Vhiilw5m5TNk4cl1IuX4eWJR%2bXXql4jHMdkWSDYGPkc3WPwmn7FzrMarQwVnL8fcaoA5LPEMLWqW6kq9VFJPa0dpFKQ9YshtJSVMxfZNgCx50I2bmE2rPHJ8zJlUsyOHC0wG3RQeyQATXMv%2f0chjeDyRW3ztH0SQPj%2bnMVFlhU6zsgWt229RfQqyn4nEcDrl%2bOc7myEu1Y7pAfDfBs%2fAeqcpXY2BQX31NapmxsNTQQK7EJSDwbsnn9M3scybfa5kdiOnFxS2JoFP%2bILDTASPt%2fYlHH7hinLhvK9%2fvU42krM5RghGonDp5%2bTUqdwW4%2bbdS%2flOF1dhrk%3d&amp;vet=745&amp;dt=081017&amp;mlid=9857647622&amp;tmpID=3340&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=62874117&amp;rt=1:

Your account was reserved for you by  in order to reserve your free trial, however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppQs7m3C8F1y61seORcP%2BPjbBQLAIgfMr3Ucw5ByHKDHF%2BAzNQQn1bXh8Nac%2Bas0iwXzq9NGU8qNNMk2SsWs5j%2BaZmzSHYkhB2QQ%2F%2BMtNY1VJqs7OscClhTPUfo9oXFlJwfuohwOMQP5CXFlRQgUHdeH&vet=745&mlid=9857647622.

No more emails from  ()? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppQs7m3C8F1y61seORcP%2BPjbBQLAIgfMr3Ucw5ByHKDHF%2BAzNQQn1bXh8Nac%2Bas0iwXzq9NGU8qNNMk2SsWs5j%2BaZmzSHYkhB2QQ%2F%2BMtNY1VJqs7OscClhTPUfo9oXFlJwfuohwOMQP5CXFlRQgUHdeH&vet=745&mlid=9857647622

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by system123** [comment]
body { -ms-text-size-adjust: none !important; font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;}

My balance: $1,000

Home

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

p

small-text

Hello,

Starting in 2016, you were an early (alpha) member of our project called empowr. Well, that project evolved and became the new www.empowr.com. Along the way, we invented virtual currency and many other technologies used by all the top social media companies.

Your free coins

As you probably know by now, empowr is launching its own coin (like Bitcoin) and, as our way of saying Thank You to the incredible community that got us here, we're giving the first coins to you – TOTALLY FREE. Read the details
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=18&amp;authToken=lgcxCm7paJ8skspvH%2fPUMWDWagRLLN0y7IDhhhi6YfWah1L%2b0YDm7cc8L%2bpdu9xVsy3NoxLtG0uvy5sRntPn8Rr%2fgbfc85TVTTZyGdlK04ru0gjok63mJ%2bl8ARM1Q5rdZdVJaAN%2b9mqmBLkJNzLq42cwnTZgWqI%2bi7xSx5o6IAyfTyTzr4QepX34Nk6MqgJCF1WA%2bu1t9LbqghUfL0ssLM3PqRD68MHi5AFIHF%2b8FhVB5Me4EWOOe9Flw%2b0NPIW%2f%2bzqnAUmntV7r5rukgjW517Ybg04cJSya2w%2fXKvyrmGxXu%2b7za2nG%2fK4YDal9RAw1&amp;PolicyAcceptance=fjijBDLjRyLExBCPz27aA6w9dfDB1bkHxI5dQAZtb8%2ft5mdQcrE2bQAfi9U4QS6GDjMftQuQkQMBcdFF9HVDJHw2SJYn6XDBx433bHhfY1UpV1%2bqDNvr7m1USe9fk%2f84s9yYeQ%2fBt2m0aibYOrg5l9JVYiykIg2ghmlCWkhFNZGVcbjMWpTzSbouMyCYyWOXztpe2swBPT9PDgvVkAxpac705vVEYLUJqgGBN57JTGLEXR4YLRq0DEtGOs614rGb6aBSE2P0PGg7jxjf4FDB60uiqMH0NEEvjAHOwvBiAmESpVI4rxSBqRgylqAV1T4hFGyn00AcJpovp2XA5%2biKOZQPgKfIfIhuhaN054a1QDR%2bZ1WfxI2MOsANLc%2fV73auJAWxNM8VljKLz68pXVvn3rbH2XRmEWqazjYVSpK7mgT035w04C9Vr%2f5RSHfueIcfo%2fB7GpQswP2CaewzvUt0OmMZrdBWZlYArj18p2%2fcXdmLvLRLYq9NXY5n4x29iQIkPwNawxVhU9p6aZ8iWhAbbZUqfscEkkoONRjmRJkFv9hhNIzrH6gS%2bYGu4avrnsk6hGkuHV7R5at38VPIjh2sU7PMK%2bRYydzEL9BPcs963KXM6hSQOwTiHMT4mCPwlSZI1WeiDZvP%2bgz%2bmK6T6vGap4berfxPz3n9PLQ1ZSFO6AeALHgJBLHQJhoSoyJ6raF%2bv8SNokjGTzy%2ft%2ff4WqfyQzu1Tz%2fh2MmIxxDBtqQ%2buWMSdCzrnHdYFs0ZOz1vVWrwHlZOC3qp5je%2fKEWjY%2bTW%2fKr2z%2b20vaqVrc3C99E3UyfmgF3QirF0OzbUiLZGX%2b%2byAfL818cUSPVER4PbaxP7kSeeX5FEuKUe9xWp28e%2fLE2rc6%2fUyQveNdeohbRULTQ3oIYUZcCtt7MXYuMMujLsUtgL%2fEESt1jZd%2ffsqOIPzJgKVxX24AoA7cXmQScMeMbAZZJR1ZdLqSmBrVLdn1u0o%2bsCTzy6p8vdNoYWGmW9Cq0%3d&amp;vet=760&amp;dt=122917&amp;mlid=10115510780&amp;tmpID=3378&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=62874117&amp;rt=1

Secure your free coins &#9658;

Note: Unclaimed coins will be auctioned off to the rest of the community. (As an early member, you get exclusive first access to bid on any unclaimed coins).

Once again, THANK YOU.
-Your friends at empowr.com

Your account was reserved for you in order to allocate your free coins, however you must agree to terms and validate before it can be utilized. By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies.

At this moment, empowr can make no guarantees about the current or future price or value of the new empowr cryptocurrency coin, or that it will be ultimately tradeable on one or more public currency exchanges. By accepting your free founder coins, you acknowledge that this offer represents a gift that can be revoked if it is found to not be legal in your state, country or jurisdiction. Vesting and other details apply.

You are receiving this gift and email because you were an alpha user of the SMS.ac / FanBox / empowr project. You can unsubscribe here
#.

-->

New! Download the empowr mobile app:

&nbsp;

&nbsp;

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: FanBox Terms and Conditions. You can prevent future emails here.
FanBox - 611 K Street, Suite B411, San Diego, CA 92101, USA

**Comment by system123** [comment]
body { -ms-text-size-adjust: none !important; font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;}

My balance: $1,000

Home

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

p

small-text

Hello,

Starting in 2016, you were an early (alpha) member of our project called empowr. Well, that project evolved and became the new www.empowr.com. Along the way, we invented virtual currency and many other technologies used by all the top social media companies.

Your free coins

As you probably know by now, empowr is launching its own coin (like Bitcoin) and, as our way of saying Thank You to the incredible community that got us here, we're giving the first coins to you – TOTALLY FREE. Read the details
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=18&amp;authToken=OCTrp1iIxEdm1Yi7Olz0SmrqwFYyCST0bemGes9mjx3yfIeMFdePG3hqjq2P8JtGyc6F4gitfDtNRq3uUx0JA0gty%2f7jHCUzNnEEEZrLOANPTJbcpzYuzlxlFSkrdIXHmIpcOJzU9zbVWMurFbDUt7UDmnPFGPjuLQVcY05%2bcYpTB7dxzI5Yk%2bN4nEh8aO98PoLyB24NilwGoVdW8R7Gv6ADVhgOlrfo8lQw26oYUu9Mg%2btLUSGTkkyRI9w449i4LQQ7X9mXRqLRJYjuMXQXBMblcE2KSvlaoV4UM07xgWzfjp4XLhT4ML9HPBSpIHtj&amp;PolicyAcceptance=BZ%2b493yUmEuSSNVMILbiLaIcdBu5QsahM5NDlDC9DiyLBCnNzoUs0kA8TB70E9S%2fy1GWjWds3M%2bPuAxQHB0gLi0AEHopT0BCNLCyaRwCRRVEZAryq%2f3WD5kLz6FeXgNo0OZ93k%2fOSzu4tpApHVhQJwj08KT%2f2KfXRgzJHNi8pOtSMNIpGR%2fOUX5tWyOVVuW5n2%2bU4cXOqxwLobcNZGsrYuk9k7pBEro3NzLBmAxrmtwGjubNFbCaLzsvnD2jxA6W3ZFlwrhG6hzIGhvaowMuhtvnfaaDzMPO0zq6FI97hgI8%2bXAKhrfKz%2fJw8k2QeJp%2b4HsoOtwn3eiMDriqmeqYneUzWAgGhYv%2bBzWe1l1VnMAfhXuwiuT2%2fcZyIXz73aVFFi6hPM4cJRpA5I9gMDbWyRSqYnK4UTdH2m3z7Vn2DrD0CTGuNzIXTWGzp%2b8DwrmSLS3my01DIkj0lrJdQW6%2fTs%2f6RXDEltq3ziyYTlV9HXPRaO76B04Z5X7znbTr4o9AM1FLYqpKFHZC54x7EM1zof4tDtLAb%2fHLqkZVDukg0xZxVtE2vXK4LZ1%2b7axyyXq9rV4e1njW5Ccf2ievZSIiJn9kcOloTKR%2bCCv2stPukt%2bp48n%2fylz5P8PJVgKGsgMPb0Kz7p2qkcClip7wwT2SdkxOAwBvw2FcZl%2fMdnJnosYCOxiYMOizOfs1WSkGQv5Y73mKwAbb%2bcHOaustDEiN1Mv%2fLQtJDBogB7NvIG9c1uQKDbVQcxx0pu216pw5LhKs6j%2b3jS%2bY%2fqSYs9gwCe10%2f975aCakvdqeoExJ%2fbFdjgaIa67UyB7RJSnqnL7sDXqmeFOinJGwotK4dZwB0OF8HKrzd5tPftZQO%2fsCbiCTgRW%2bHNIe1TpixrHuzgVQDo42EzXvfZHE%2fgde9lvBreEmk0myrMyLNwkzti7I%2fYKgmaY%3d&amp;vet=760&amp;dt=021018&amp;mlid=10273423016&amp;tmpID=3378&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=62874117&amp;rt=1

Secure your free coins &#9658;

Note: Unclaimed coins will be auctioned off to the rest of the community. (As an early member, you get exclusive first access to bid on any unclaimed coins).

Once again, THANK YOU.
-Your friends at empowr.com

Your account was reserved for you in order to allocate your free coins, however you must agree to terms and validate before it can be utilized. By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies.

At this moment, empowr can make no guarantees about the current or future price or value of the new empowr cryptocurrency coin, or that it will be ultimately tradeable on one or more public currency exchanges. By accepting your free founder coins, you acknowledge that this offer represents a gift that can be revoked if it is found to not be legal in your state, country or jurisdiction. Vesting and other details apply.

You are receiving this gift and email because you were an alpha user of the SMS.ac / FanBox / empowr project. You can unsubscribe here
#.

-->

New! Download the empowr mobile app:

&nbsp;

&nbsp;

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: FanBox Terms and Conditions. You can prevent future emails here.
FanBox - 611 K Street, Suite B411, San Diego, CA 92101, USA
